# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test plugp100 library

on:
  push:
    branches:
      - "test-ci"

jobs:
  dependecies_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
          - arch: armv7
            distro: ubuntu20.04

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: "Test plugp100 dependencies"
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          install: |
            apt-get update -y
            apt-get install -y software-properties-common
            add-apt-repository ppa:deadsnakes/ppa
            apt-get install -y python3.9 python3.9-distutils curl
            curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            python3.9 get-pip.py --user
          run: |
            ls /root/.local/bin/
            /root/.local/bin/pip3.9 install -r requirements.txt
